code = open('lib/noaa.js').read()[:10]
print('test read:', code[:20])

db_code = (
    "const{createClient}=require('@supabase/supabase-js');\n"
    "let _client=null;\n"
    "function getDB(){\n"
    "  if(!_client){\n"
    "    const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_KEY;\n"
    "    if(!url||!key)throw new Error('Missing env vars');\n"
    "    _client=createClient(url,key);\n"
    "  }\n"
    "  return _client;\n"
    "}\n"
    "async function saveOceanData(date,data){\n"
    "  const db=getDB();\n"
    "  const{error}=await db.from('ocean_data').upsert({date,\n"
    "    sst_grid:data.sstGrid?Array.from(data.sstGrid):null,\n"
    "    chl_grid:data.chlGrid?Array.from(data.chlGrid):null,\n"
    "    depth_grid:data.depthGrid?Array.from(data.depthGrid):null,\n"
    "    gs_grid:data.gsGrid?Array.from(data.gsGrid):null,\n"
    "    isotherms:data.isotherms||null,temp_breaks:data.tempBreaks||null,\n"
    "    waypoints:data.waypoints||null,sst_date:data.sstDate||null,\n"
    "    chl_date:data.chlDate||null,updated_at:new Date().toISOString(),\n"
    "  },{onConflict:'date'});\n"
    "  if(error)throw error;\n"
    "  return true;\n"
    "}\n"
    "async function getLatestOceanData(){\n"
    "  const db=getDB();\n"
    "  const{data,error}=await db.from('ocean_data').select('*').order('date',{ascending:false}).limit(1).single();\n"
    "  if(error)throw error;\n"
    "  return data;\n"
    "}\n"
    "async function getOceanDataByDate(date){\n"
    "  const db=getDB();\n"
    "  const{data,error}=await db.from('ocean_data').select('*').eq('date',date).single();\n"
    "  if(error)return null;\n"
    "  return data;\n"
    "}\n"
    "async function saveBuoyData(buoys){\n"
    "  const db=getDB();\n"
    "  const rows=buoys.map(b=>({\n"
    "    buoy_id:b.id,name:b.name,lat:b.lat,lon:b.lon,timestamp:b.timestamp,\n"
    "    wind_speed:b.wind&&b.wind.speed,wind_dir:b.wind&&b.wind.dir,\n"
    "    wind_gust:b.wind&&b.wind.gust,wave_height:b.waves&&b.waves.height,\n"
    "    wave_period:b.waves&&b.waves.period,sst:b.sst,air_temp:b.airTemp,\n"
    "    pressure:b.pressure,fetched_at:new Date().toISOString()}));\n"
    "  const{error}=await db.from('buoy_data').upsert(rows,{onConflict:'buoy_id,timestamp'});\n"
    "  if(error)console.warn('Buoy error:',error.message);\n"
    "}\n"
    "async function getLatestBuoys(){\n"
    "  const db=getDB();\n"
    "  const{data,error}=await db.from('buoy_data').select('*').order('fetched_at',{ascending:false}).limit(20);\n"
    "  if(error)throw error;\n"
    "  const seen=new Set();\n"
    "  return(data||[]).filter(b=>{\n"
    "    if(seen.has(b.buoy_id))return false;\n"
    "    seen.add(b.buoy_id);return true;});\n"
    "}\n"
    "module.exports={getDB,saveOceanData,getLatestOceanData,getOceanDataByDate,saveBuoyData,getLatestBuoys};\n"
)

with open('lib/db.js','w') as f:
    f.write(db_code)
print('db.js written, size:', len(db_code))
